var piglet = { character: "Piglet"};
var eeyore = { character: "Eeyore"};
var heffalumps = { character: "Heffalumps"};
var kanga = { character: "Kanga"};
var owl = { character: "Owl"};
var chris = { character: "Christopher Robin"};
var rabbit = { character: "Rabbit"};
var gopher = { character: "Gopher"};
var pooh = { character: "Winnie The Pooh"};
var bees= { character: "Bees"};
var tigger = { character: "Tigger"};
var player = {
    location: tigger
}
tigger.north = pooh;
pooh.north = chris;
pooh.south = tigger;
pooh.west = piglet;
pooh.east = bees;
piglet.north = owl;
piglet.east = pooh;
bees.west = pooh;
bees.north = rabbit;
owl.south = piglet;
owl.east =chris;
chris.north =kanga;
chris.south = pooh;
chris.west = owl;
chris.east = rabbit;
rabbit.west = chris;
rabbit.south = rabbit;
rabbit.east = gopher;
gopher.west = rabbit;
kanga.south = chris;
kanga.north = eeyore;
eeyore.south = kanga;
eeyore.east = heffalumps;
heffalumps.west = eeyore;